polls/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from poll.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("poll.urls")),
    path("", HomeView.as_view(), name="home"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/poll/urls.py
from django.urls import path
from .views import *

app_name = "poll"

# path("경로",뷰,name="별칭")
# 뷰  1) 함수형 뷰 2) 클래스 뷰

urlpatterns = [
    path("", index, name="index"),
    path("<int:question_id>/", detail, name="detail"),
    path("<int:question_id>/vote/", vote, name="vote"),
    path("<int:question_id>/results/", results, name="results"),
]

polls/poll/models.py
from django.db import models

# 설문조사 앱
# 질문 / 선택 답변


# 질문 : 번호,질문내용,작성일
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    creates_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text


# 답변 : 외래키,답변내용,투표수
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/poll/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.views.generic.base import TemplateView
from .models import *


# 클래스 뷰
class HomeView(TemplateView):
    template_name = "home.html"


# 함수형 뷰
# HttpResponse 객체 리턴
# render(request,템플릿명) 리턴
# redirect() 리턴


def index(request):
    # return HttpResponse("Hello")

    # 전체 question 조회
    question = Question.objects.all()
    return render(request, "poll/index.html", {"question": question})


def detail(request, question_id):
    # get() : 원하는 정보를 찾지 못하는 경우 DoesNotExist 발생
    # try:
    #     question = Question.objects.get(id=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question id를 확인해 주세요")
    question = get_object_or_404(Question, id=question_id)
    return render(request, "poll/detail.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    # post
    if request.method == "POST":
        # 사용자가 선택한 choice 가져오기
        selected_choice = request.POST.get("choice")
        # choice 테이블에서 vote 추가하기
        # Choice 찾기
        # Choice.objects.get() or get_object_or_404(Choice, id=choice)
        choice = question.choice_set.get(id=selected_choice)
        choice.votes += 1
        choice.save()

        return redirect("poll:results", question_id=question.id)


def results(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    return render(request, "poll/results.html", {"question": question})

polls/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/> {% endcomment %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    {% block style %}{% endblock style %}
    {% block title %}{% endblock title %}
  </head>

  <body>
    <div class="container mt-5">
      {% block content %}{% endblock content %}
    </div>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> {% endcomment %}
    <source src="{% static "js/bootstrap.bundle.min.js" %}" type="">
    {% block script %}{% endblock script %}
  </body>

</html>

polls/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h1>HOME</h1>
  <ul>
    <li>
      <a href="{% url "poll:index" %}">index</a>
    </li>
  </ul>
{% endblock content %}

polls/templates/poll/detail.html
{% extends "base.html" %}
{% block content %}
  <h4>상세보기</h4>
  <form action="{% url "poll:vote" question_id=question.id%}" method="post">
    {% csrf_token %}
    <fieldset class="form-group border p-3 mb-3">
      <legend class="w-auto px-2">
        <h3>{{question.question_text}}</h3>
      </legend>
      <p>
        <strong></strong>
      </p>
      {% comment %} question 쪽에서 choice 접근하기기 {% endcomment %}
      {% for choice in question.choice_set.all %}
      <div>
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
      </div>
      {% endfor %}
    </fieldset>
    <button type="submit" class="btn btn-info">vote</button>
  </form>
{% endblock content %}

polls/templates/poll/index.html
{% extends "base.html" %}
{% block content %}
  <div class="card">
    <div class="card-header">
      익명투표 결과
    </div>
    <ul class="list-group list-group-flush">
      {% for q in question %}
        <li class="list-group-item">
          <a href="{% url "poll:detail" q.id%}">{{q.question_text}}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}

polls/templates/poll/results.html
{% extends "base.html" %}
{% block content %}
  <div class="card">
    <div class="card-header">
      익명투표 결과 -
      {{question.question_text}}
    </div>
    <ul class="list-group list-group-flush">
      {% for choice in question.choice_set.all %}
        <li class="list-group-item">
          {{choice.choice_text}}
          --
          {{choice.votes}}
        </li>
      {% endfor %}
    </ul>
  </div>
  <div class="mt-3">
    <a href="{% url "poll:detail" question.id%}">재투표</a>
  </div>
</div>
{% endblock content %}