boardapp/board/urls.py
from django.urls import path
from .views.base_views import *
from .views.question_views import *
from .views.answer_views import *
from .views.comment_views import *
from .views.vote_views import *

app_name = "board"

urlpatterns = [
    path("", index, name="index"),
    #### 질문
    path("qusetion/<int:id>/", detail, name="detail"),
    path("qusetion/create/", create, name="create"),
    path("qusetion/modify/<int:id>/", modify, name="modify"),
    path("qusetion/delete/<int:id>/", delete, name="delete"),
    #### 답변
    path("answer/create/<int:id>/", answer_create, name="answer_create"),
    path("answer/modify/<int:id>/", answer_modify, name="answer_modify"),
    path("answer/delete/<int:id>/", answer_delete, name="answer_delete"),
    #### 질문 댓글
    path("comment/create/question/<int:id>/", comment_create_question, name="ccq"),
    path("comment/modify/question/<int:id>/", comment_modify_question, name="cmq"),
    path("comment/delete/question/<int:id>/", comment_delete_question, name="cdq"),
    #### 답변 댓글
    path("comment/create/answer/<int:id>/", comment_create_answer, name="cca"),
    path("comment/modify/answer/<int:id>/", comment_modify_answer, name="cma"),
    path("comment/delete/answer/<int:id>/", comment_delete_answer, name="cda"),
    #### 질문 추천
    path("question/vote/<int:question_id>/", vote_question, name="vq"),
    #### 답변 추천
    path("answer/vote/<int:answer_id>/", vote_answer, name="va"),
]

boardapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views.base_views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("", index),
]

boardapp/users/urls.py
from django.urls import path, reverse_lazy
from .views import register, CustomPasswordResetView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # 비밀번호 변경(변경+세션에 있는 비밀번호 업데이트)
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("board:index"),
        ),
        name="password_change",
    ),
    # 비밀번호 초기화
    # 단계 1) 사용자에게 이메일 주소 입력받기
    path(
        "password_reset/",
        CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

boardapp/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, QuestionCount
from tools.utils import get_client_ip
from django.core.paginator import Paginator
from django.db.models import Q, Count


def detail(request, id):
    page = request.GET.get("page", 1)

    keyword = request.GET.get("keyword", "")

    so = request.GET.get("so", "")
    question = get_object_or_404(Question, id=id)

    # 조회수
    ip = get_client_ip(request)
    # question에 동일한 ip가 있는지 확인
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        qc = QuestionCount(ip=ip, question=question)
        qc.save()
        if question.view_cut:
            question.view_cut += 1
        else:
            question.view_cut = 1
        question.save()

    context = {
        "question": question,
        "page": page,
        "keyword": keyword,
        "so": so,
    }

    return render(request, "board/question_detail.html", context)


def index(request):

    page = request.GET.get("page", 1)

    keyword = request.GET.get("keyword", "")

    so = request.GET.get("so", "")

    # 전체 질문 추출(작성일시 내림차순)
    if so == "recommend":
        objects = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-created_at"
        )
    elif so == "popular":
        objects = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:
        objects = Question.objects.order_by("-created_at")

    # 검색어가 제목 or 내용 or 질문작성자 or 답변작성자에 포함된 경우 추출
    # or : Q 사용
    if keyword:
        objects = objects.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(objects, 10)  # 페이징 처리
    max_page = len(paginator.page_range)  # 마지막 페이지

    question_list = paginator.get_page(page)  # 페이지 생성 객체

    context = {
        "question_list": question_list,
        "max_page": max_page,
        "page": page,
        "keyword": keyword,
        "so": so,
    }
    return render(request, "board/question_list.html", context)

boardapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    {% comment %} <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"> {% endcomment %} 
    {% block style %}{% endblock style %} 
    {% block title %}{% endblock title %}
  </head>

  <body>
    {% include "navbar.html" %}
    <div class="container mt-5">{% block content %}{% endblock content %}</div>
    <form action="{% url "users:logout" %}" method="post" id="logoutForm">
      {% csrf_token %}
    </form>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script>
      document.querySelector("#logout").addEventListener("click", (e) => {
          e.preventDefault();
          document.querySelector("#logoutForm").submit();
      });
  </script>
    {% block script %}{% endblock script %}
  </body>
</html>

boardapp/templates/form_errors.html
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      {% if field.errors %}
        <strong>{{field.label}}</strong>
        {{field.errors}}
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

boardapp/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "board:index" %}">Board</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "board:index" %}">Home</a>
        </li>
         
        
        <li class="nav-item dropdown">

          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            회원
          </a>
          
          <ul class="dropdown-menu">
            {% if not user.is_authenticated %}
            <li>
              <a class="dropdown-item" href="{% url "users:register" %}">회원가입</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url "users:login" %}">로그인</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url "users:password_reset" %}">비밀번호 초기화</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            {% else %}
            <li>
              <a class="dropdown-item" href="#" id="logout">로그아웃</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url "users:password_change" %}">비밀번호 변경</a>
            </li>
            {% endif %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">{{request.user}}</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>