usersapp/book/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    # http://127.0.0.1:8000/books/ 전체도서목록(list)
    path("", views.book_list, name="list"),
    # http://127.0.0.1:8000/books/1/ 도서조회(detail)
    path("<int:id>/detail/", views.book_deatail, name="detail"),
    # http://127.0.0.1:8000/books/1/edit/ 도서수정(edit)
    path("<int:id>/edit/", views.book_edit, name="edit"),
    # http://127.0.0.1:8000/books/1/remove 도서삭제(remove)
    path("<int:id>/remove/", views.book_remove, name="remove"),
    # http://127.0.0.1:8000/books/create 도서추가(create)
    path("create/", views.book_create, name="create"),
]

usersapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("books/", include("book.urls")),
    # RedirectView == redirect()
    path("", RedirectView.as_view(pattern_name="users:home")),
]

usersapp/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("", views.home, name="home"),
    # login,logout 직접 작성시
    # path("login/", views.users_login, name="login"),
    # path("login/", views.users_login, name="login"),
    # 장고의 auth가 제공하느 login,logout class view 를 사용
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("register/", views.user_register, name="register"),
]

usersapp/book/models.py
from django.db import models


class Book(models.Model):
    """
    code(숫자),title,author,price(숫자),create_at
    """

    code = models.IntegerField(
        verbose_name="도서코드", unique=True, help_text="코드는 숫자 4자리로 작성하세요"
    )
    title = models.CharField(max_length=200, verbose_name="도서명")
    author = models.CharField(max_length=100, verbose_name="저자")
    price = models.IntegerField(
        verbose_name="도서가격", help_text="최소 1000원 이상이어야합니다."
    )
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="등록일시")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "booktbl"

usersapp/book/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"
        exclude_fields = ["created_at"]

usersapp/book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book
from .forms import BookForm


def book_list(request):
    book = Book.objects.order_by("-id")
    return render(request, "book/list.html", {"book": book})


def book_deatail(request, id):
    book = get_object_or_404(Book, id=id)
    return render(request, "book/detail.html", {"book": book})


def book_edit(request, id):
    book = get_object_or_404(Book, id=id)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect("books:detail", id=id)

    else:
        form = BookForm(instance=book)
    return render(request, "book/edit.html", {"form": form, "id": id})


def book_create(request):

    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save()
            return redirect("books:detail", id=book.id)

    else:
        form = BookForm()
    return render(request, "book/create.html", {"form": form})


def book_remove(request, id):
    book = get_object_or_404(Book, id=id)
    book.delete()
    return redirect("books:list")

usersapp/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserRegisterForm


def home(request):
    return render(request, "home.html")


def users_login(request):
    if request.method == "POST":
        # username, password 가져오기
        username = request.POST.get("username")
        password = request.POST.get("password")

        # db 정보와 일치한다면 인증받은 객체 user 리턴
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)  # 세션에 user 정보 담기
            return redirect("users:home")

    return render(request, "users/login.html")


def users_logout(request):
    logout(request)
    return redirect("users:home")


def user_register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("users:login")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})

usersapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    {% comment %} <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"> {% endcomment %}
    {% block style %}{% endblock style %}
    {% block title %}{% endblock title %}
  </head>

  <body>
    {% include "navbar.html" %}
    <div class="container mt-5">
      {% block content %}{% endblock content %}
    </div>
    <form action="{% url "users:logout" %}" method="post" id="logoutForm">
      {% csrf_token %}
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% comment %} <source src="{% static "js/bootstrap.bundle.min.js" %}" type=""> {% endcomment %}
    <script>
      document.querySelector("#logout").addEventListener("click", (e) => {
          e.preventDefault();
          document.querySelector("#logoutForm").submit();
      });
  </script>
    {% block script %}{% endblock script %}
  </body>

</html>

usersapp/templates/book/create.html
{% extends "base.html" %}
{% block content %}
  <form method="post" action="">
    {% include "form_errors.html" %}
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group mb-3">
        <label for="{{field.id_for_label}}">{{field.label}}</label>
        <input type="{{field.widget_type}}" class="form-control" id="{{field.id_for_label}}" name="{{field.name}}" placeholder="{{field.label}}" value="{{field.value|default_if_none:''}}">
        <span class="text-danger small">{{field.help_text}}</span>
      </div>
    {% endfor %}
    {% if user.is_authenticated and user.is_superuser %}
      <button type="submit" class="btn btn-outline-secondary">등록</button>
    {% endif %}
    <a href="{% url "books:list" %}" class="btn btn-outline-dark">목록</a>
  </form>
{% endblock content %}

usersapp/templates/book/detail.html
{% extends "base.html" %}
{% block content %}
  <form method="post" action="">
    <div class="mb-3">
      <label for="code" class="form-label">도서 코드</label>
      <input type="text" class="form-control" id="code" name="code" value="{{book.code}}" readonly="readonly">
    </div>
    <div class="mb-3">
      <label for="title" class="form-label">도서 명</label>
      <input type="text" class="form-control" id="title" name="title" value="{{book.title}}" readonly="readonly">
    </div>
    <div class="mb-3">
      <label for="author" class="form-label">도서 저자</label>
      <input type="text" class="form-control" id="author" name="author" value="{{book.author}}" readonly="readonly">
    </div>
    <div class="mb-3">
      <label for="price" class="form-label">도서 가격</label>
      <input type="text" class="form-control" id="price" name="price" value="{{book.price}}" readonly="readonly">
    </div>
    <div class="mb-3">
      <label for="create_at" class="form-label">등록일</label>
      <input type="text" class="form-control" id="create_at" name="create_at" value="{{book.create_at}}" readonly="readonly">
    </div>
    {% if user.is_authenticated and user.is_superuser %}
      <a href="{% url "books:edit" book.id %}" class="btn btn-outline-secondary">수정</a>
    {% endif %}
    <a href="{% url "books:list" %}" class="btn btn-outline-dark">목록</a>
  </form>
{% endblock content %}

usersapp/templates/book/edit.html
{% extends "base.html" %}
{% block content %}
  <form method="post" action="">
    {% include "form_errors.html" %}
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group mb-3">
        <label for="{{field.id_for_label}}">{{field.label}}</label>
        <input type="{{field.widget_type}}" class="form-control" id="{{field.id_for_label}}" name="{{field.name}}" placeholder="{{field.label}}" value="{{field.value|default_if_none:''}}">
        <span class="text-danger small">{{field.help_text}}</span>
      </div>
    {% endfor %}
    {% if user.is_authenticated and user.is_superuser %}
      <button type="submit" class="btn btn-outline-secondary">수정</button>
      <a href="{% url "books:remove" id=id%}" class="btn btn-outline-danger">삭제</a>
    {% endif %}
    <a href="{% url "books:list" %}" class="btn btn-outline-dark">목록</a>
  </form>
{% endblock content %}

usersapp/templates/book/list.html
{% extends "base.html" %}
{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">도서코드</th>
        <th scope="col">도서명</th>
        <th scope="col">저자</th>
      </tr>
    </thead>
    <tbody>
      {% for b in book %}
        <tr>
          <th scope="row">{{b.id}}</th>
          <td>{{b.code}}</td>
          <td>
            <a href="{% url "books:detail" b.id%}" class="text-decoration-none text-reset">{{b.title}}</a>
          </td>
          <td>{{b.author}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

usersapp/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "users:home" %}">Home</a>
        </li>
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "users:login" %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "users:register" %}">Register</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" id="logout">Logout</a>
          </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Book
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url "books:list" %}">List</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url "books:create" %}">Create</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>